### PR TITLE
Fix password recovery validation

### PR DESCRIPTION
**Pull request by TeTiRoss**

### CODE REVIEW

**Review by ruslantolstov — APPROVED** [review]

**Comment by TeTiRoss** [comment]
@DmytroStepaniuk ping

**Comment by DmytroStepaniuk** [comment]
> @DmytroStepaniuk ping

pong

**Comment by DmytroStepaniuk** [comment]
@TeTiRoss need to figure out why does tests fail 🤔

**Comment by TeTiRoss** [comment]
@DmytroStepaniuk specs are fixed.

**Review by DmytroStepaniuk — APPROVED** [review]
It's ok, just need to notify guys to not use `master` branch.

**Pull request merged**
